/** Domain columns are explicit. JSON is reserved for provider extensions and snapshots. */
export const entityDefinitions: Record<string, { table: string; project: boolean; columns: string; constraints?: string }> = {
  project: { table: 'projects', project: false, columns: 'name TEXT NOT NULL, type TEXT, priority TEXT, description TEXT, hidden INTEGER NOT NULL DEFAULT 0 CHECK(hidden IN (0,1)), pinned_at INTEGER' },
  roadmap_node: { table: 'roadmap_nodes', project: true, columns: 'local_node_id TEXT NOT NULL, title TEXT NOT NULL, description TEXT, stage TEXT, order_key REAL NOT NULL DEFAULT 0, status TEXT NOT NULL, agent_cli TEXT, agent_prompt_content_id TEXT REFERENCES contents(id), completed_at INTEGER', constraints: 'UNIQUE(project_id,local_node_id)' },
  file_binding: { table: 'file_bindings', project: true, columns: 'role TEXT NOT NULL, relative_path TEXT NOT NULL, accepted_hash TEXT, exported_revision INTEGER, pending_revision INTEGER, last_error TEXT', constraints: 'UNIQUE(project_id,role,relative_path)' },
  document: { table: 'documents', project: true, columns: 'file_binding_id TEXT NOT NULL REFERENCES file_bindings(id), role TEXT NOT NULL, status TEXT NOT NULL, solves TEXT, last_reviewed_at INTEGER' },
  asset: { table: 'assets', project: true, columns: 'name TEXT NOT NULL, content_id TEXT REFERENCES contents(id), file_binding_id TEXT REFERENCES file_bindings(id), origin TEXT, sha256 TEXT', constraints: 'CHECK((content_id IS NULL) <> (file_binding_id IS NULL))' },
  integration: { table: 'integrations', project: false, columns: 'kind TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL, package_version_id TEXT REFERENCES package_versions(id), config_content_id TEXT REFERENCES contents(id), secret_ref TEXT, health_content_id TEXT REFERENCES contents(id)' },
  package_version: { table: 'package_versions', project: false, columns: 'package_key TEXT NOT NULL, version TEXT NOT NULL, source TEXT NOT NULL, digest TEXT NOT NULL, installed_relative_path TEXT NOT NULL', constraints: 'UNIQUE(package_key,version,digest)' },
  conversation: { table: 'conversations', project: true, columns: 'parent_conversation_id TEXT REFERENCES conversations(id), node_id TEXT REFERENCES roadmap_nodes(id), mode TEXT NOT NULL, status TEXT NOT NULL, title TEXT NOT NULL' },
  message: { table: 'messages', project: true, columns: 'conversation_id TEXT NOT NULL REFERENCES conversations(id), sequence INTEGER NOT NULL, role TEXT NOT NULL, content_id TEXT NOT NULL REFERENCES contents(id), turn_id TEXT REFERENCES turns(id)', constraints: 'UNIQUE(conversation_id,sequence)' },
  task: { table: 'tasks', project: true, columns: 'conversation_id TEXT NOT NULL REFERENCES conversations(id), node_id TEXT REFERENCES roadmap_nodes(id), original_request_content_id TEXT NOT NULL REFERENCES contents(id), criteria_content_id TEXT REFERENCES contents(id), status TEXT NOT NULL' },
  turn: { table: 'turns', project: true, columns: 'task_id TEXT NOT NULL REFERENCES tasks(id), sequence INTEGER NOT NULL, request_content_id TEXT NOT NULL REFERENCES contents(id), outcome TEXT, summary_content_id TEXT REFERENCES contents(id), started_at INTEGER NOT NULL, finished_at INTEGER', constraints: 'UNIQUE(task_id,sequence)' },
  run: { table: 'runs', project: true, columns: 'task_id TEXT NOT NULL REFERENCES tasks(id), turn_id TEXT REFERENCES turns(id), conversation_id TEXT NOT NULL REFERENCES conversations(id), location_id TEXT NOT NULL REFERENCES project_locations(id), run_kind TEXT NOT NULL, actor_id TEXT NOT NULL REFERENCES actors(id), command_content_id TEXT REFERENCES contents(id), prompt_content_id TEXT REFERENCES contents(id), status TEXT NOT NULL, started_at INTEGER NOT NULL, finished_at INTEGER, duration_ms INTEGER, exit_code INTEGER, input_tokens INTEGER, cached_input_tokens INTEGER, output_tokens INTEGER, reasoning_output_tokens INTEGER, total_tokens INTEGER, usage_json TEXT' },
  evidence: { table: 'evidence', project: true, columns: 'run_id TEXT REFERENCES runs(id), type TEXT NOT NULL, source_actor_id TEXT NOT NULL REFERENCES actors(id), content_id TEXT REFERENCES contents(id), file_binding_id TEXT REFERENCES file_bindings(id), observed_at INTEGER NOT NULL, source_revision INTEGER', constraints: 'CHECK(content_id IS NOT NULL OR file_binding_id IS NOT NULL)' },
  verification: { table: 'verifications', project: true, columns: 'task_id TEXT NOT NULL REFERENCES tasks(id), run_id TEXT REFERENCES runs(id), verifier_actor_id TEXT NOT NULL REFERENCES actors(id), claim TEXT NOT NULL, result TEXT NOT NULL, evidence_id TEXT NOT NULL REFERENCES evidence(id), verified_at INTEGER NOT NULL' },
  report: { table: 'reports', project: true, columns: 'turn_id TEXT NOT NULL REFERENCES turns(id), run_id TEXT REFERENCES runs(id), schema_version INTEGER NOT NULL, content_id TEXT NOT NULL REFERENCES contents(id), availability TEXT NOT NULL, validation_error TEXT' },
  workflow_loop: { table: 'workflow_loops', project: true, columns: 'task_id TEXT NOT NULL REFERENCES tasks(id), sequence INTEGER NOT NULL, goal TEXT NOT NULL, status TEXT NOT NULL, planner_run_id TEXT REFERENCES runs(id), builder_run_id TEXT REFERENCES runs(id), verifier_run_id TEXT REFERENCES runs(id), scoring_content_id TEXT REFERENCES contents(id)', constraints: 'UNIQUE(task_id,sequence)' },
  memory: { table: 'memories', project: false, columns: 'category TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL, confidence REAL NOT NULL DEFAULT 0 CHECK(confidence BETWEEN 0 AND 1), content_id TEXT NOT NULL REFERENCES contents(id), valid_until INTEGER, external_source TEXT, external_revision TEXT, canonical_hash TEXT' },
  learning_event: { table: 'learning_events', project: false, columns: 'source_object_id TEXT NOT NULL REFERENCES objects(id), event_type TEXT NOT NULL, summary TEXT NOT NULL, occurred_at INTEGER NOT NULL, source_revision INTEGER NOT NULL', constraints: 'UNIQUE(source_object_id,event_type,source_revision)' },
  lesson: { table: 'lessons', project: false, columns: 'status TEXT NOT NULL, summary TEXT NOT NULL, applies_when TEXT, does_not_apply_when TEXT, do_this TEXT, avoid_this TEXT, verification TEXT, confidence REAL NOT NULL DEFAULT 0 CHECK(confidence BETWEEN 0 AND 1)' },
  lesson_decision: { table: 'lesson_decisions', project: false, columns: 'event_id TEXT NOT NULL REFERENCES learning_events(id), lesson_id TEXT REFERENCES lessons(id), decision TEXT NOT NULL, reason TEXT NOT NULL, actor_id TEXT NOT NULL REFERENCES actors(id)' },
  review_batch: { table: 'review_batches', project: false, columns: 'input_cursor INTEGER NOT NULL, input_hash TEXT NOT NULL, proposal_content_id TEXT REFERENCES contents(id), review_content_id TEXT REFERENCES contents(id), status TEXT NOT NULL' },
  application: { table: 'applications', project: false, columns: 'review_id TEXT REFERENCES review_batches(id), lesson_id TEXT REFERENCES lessons(id), target_object_id TEXT NOT NULL REFERENCES objects(id), expected_revision INTEGER NOT NULL, before_content_id TEXT REFERENCES contents(id), after_content_id TEXT NOT NULL REFERENCES contents(id), status TEXT NOT NULL, applied_revision INTEGER' },
  policy: { table: 'policies', project: false, columns: 'kind TEXT NOT NULL, status TEXT NOT NULL, content_id TEXT NOT NULL REFERENCES contents(id)' },
  policy_use: { table: 'policy_uses', project: true, columns: 'policy_id TEXT NOT NULL REFERENCES policies(id), policy_revision INTEGER NOT NULL, lesson_id TEXT REFERENCES lessons(id), lesson_revision INTEGER, run_id TEXT NOT NULL REFERENCES runs(id), purpose TEXT NOT NULL', constraints: 'FOREIGN KEY(policy_id,policy_revision) REFERENCES object_revisions(object_id,revision), FOREIGN KEY(lesson_id,lesson_revision) REFERENCES object_revisions(object_id,revision)' },
  evaluation: { table: 'evaluations', project: true, columns: 'policy_use_id TEXT NOT NULL REFERENCES policy_uses(id), verification_id TEXT REFERENCES verifications(id), feedback_event_id TEXT REFERENCES learning_events(id), metric TEXT NOT NULL, value REAL, unit TEXT, baseline_ref TEXT, verdict TEXT NOT NULL', constraints: 'CHECK(verification_id IS NOT NULL OR feedback_event_id IS NOT NULL)' },
  setting: { table: 'settings', project: false, columns: 'namespace TEXT NOT NULL, key TEXT NOT NULL, owner_scope TEXT NOT NULL, content_id TEXT REFERENCES contents(id), secret_ref TEXT', constraints: 'UNIQUE(namespace,key,owner_scope), CHECK((content_id IS NULL) <> (secret_ref IS NULL))' },
  runtime_instance: { table: 'runtime_instances', project: false, columns: 'device_id TEXT NOT NULL REFERENCES devices(id), pid INTEGER NOT NULL, process_started_at INTEGER NOT NULL, status TEXT NOT NULL, build_id TEXT NOT NULL, heartbeat_at INTEGER NOT NULL' },
  schedule: { table: 'schedules', project: false, columns: 'timezone TEXT NOT NULL, trigger_spec_json TEXT NOT NULL, enabled INTEGER NOT NULL CHECK(enabled IN (0,1)), next_due_at INTEGER, task_template_content_id TEXT NOT NULL REFERENCES contents(id)' },
  grant: { table: 'grants', project: false, columns: 'actor_id TEXT NOT NULL REFERENCES actors(id), target_id TEXT NOT NULL REFERENCES objects(id), action_set_json TEXT NOT NULL, revision INTEGER NOT NULL, status TEXT NOT NULL, valid_until INTEGER' },
  growth_snapshot: { table: 'growth_snapshots', project: true, columns: 'git_head TEXT, reason TEXT NOT NULL, status TEXT NOT NULL, duration_ms INTEGER, created_at INTEGER NOT NULL' }
};

export function unifiedSchemaSql(): string {
  const base = `
CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,checksum TEXT NOT NULL,applied_at INTEGER NOT NULL);
CREATE TABLE database_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE objects(id TEXT PRIMARY KEY,kind TEXT NOT NULL,project_id TEXT REFERENCES projects(id),revision INTEGER NOT NULL CHECK(revision>0),created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,archived_at INTEGER,UNIQUE(id,kind),UNIQUE(id,project_id));
CREATE TABLE devices(id TEXT PRIMARY KEY,name TEXT NOT NULL,environment TEXT NOT NULL,credential_ref TEXT,last_seen_at INTEGER);
CREATE TABLE actors(id TEXT PRIMARY KEY,kind TEXT NOT NULL,provider TEXT,identity_ref TEXT,authority_id TEXT REFERENCES actors(id));
CREATE TABLE project_locations(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),device_id TEXT NOT NULL REFERENCES devices(id),root_path TEXT NOT NULL,status TEXT NOT NULL,UNIQUE(id,project_id));
CREATE UNIQUE INDEX active_project_location ON project_locations(device_id,root_path) WHERE status='active';
CREATE TABLE contents(id TEXT PRIMARY KEY,sha256 TEXT NOT NULL CHECK(length(sha256)=64),mime_type TEXT NOT NULL,encoding TEXT NOT NULL,byte_length INTEGER NOT NULL CHECK(byte_length>=0),stored_byte_length INTEGER NOT NULL CHECK(stored_byte_length>=0),data BLOB NOT NULL,chunk_index_json TEXT,CHECK((encoding LIKE 'chunked:%' AND length(data)=0 AND chunk_index_json IS NOT NULL) OR (encoding NOT LIKE 'chunked:%' AND length(data)=stored_byte_length AND chunk_index_json IS NULL)),UNIQUE(sha256,mime_type,encoding));
CREATE TABLE content_chunks(content_id TEXT NOT NULL REFERENCES contents(id),ordinal INTEGER NOT NULL CHECK(ordinal>=0),data BLOB NOT NULL CHECK(length(data)>0 AND length(data)<=65536),PRIMARY KEY(content_id,ordinal));
CREATE TABLE object_revisions(object_id TEXT NOT NULL REFERENCES objects(id),revision INTEGER NOT NULL,content_id TEXT NOT NULL REFERENCES contents(id),actor_id TEXT NOT NULL REFERENCES actors(id),reason TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(object_id,revision));
CREATE TABLE relations(source_id TEXT NOT NULL REFERENCES objects(id),relation TEXT NOT NULL,target_id TEXT NOT NULL REFERENCES objects(id),PRIMARY KEY(source_id,relation,target_id));
CREATE TABLE migration_items(source_identity TEXT NOT NULL,source_key TEXT NOT NULL,source_hash TEXT NOT NULL,object_id TEXT REFERENCES objects(id),imported_revision INTEGER,stage TEXT NOT NULL,error TEXT,source_content_id TEXT REFERENCES contents(id),source_capture_revision INTEGER NOT NULL DEFAULT 0 CHECK(source_capture_revision>=0),source_capture_request_id TEXT REFERENCES requests(id),PRIMARY KEY(source_identity,source_key));
CREATE TABLE roadmap_dependencies(node_id TEXT NOT NULL REFERENCES roadmap_nodes(id),dependency_id TEXT NOT NULL REFERENCES roadmap_nodes(id),PRIMARY KEY(node_id,dependency_id));
CREATE TABLE session_bindings(conversation_id TEXT NOT NULL REFERENCES conversations(id),binding_revision INTEGER NOT NULL,provider TEXT NOT NULL,native_session_id TEXT,state TEXT NOT NULL,contract TEXT,evidence_id TEXT REFERENCES evidence(id),provider_context_content_id TEXT REFERENCES contents(id),PRIMARY KEY(conversation_id,binding_revision));
CREATE TABLE log_chunks(run_id TEXT NOT NULL REFERENCES runs(id),stream TEXT NOT NULL,sequence INTEGER NOT NULL,content_id TEXT NOT NULL REFERENCES contents(id),recorded_at INTEGER NOT NULL,byte_offset INTEGER NOT NULL,PRIMARY KEY(run_id,stream,sequence));
CREATE TABLE run_changes(run_id TEXT NOT NULL REFERENCES runs(id),relative_path TEXT NOT NULL,role TEXT NOT NULL,change_kind TEXT,before_content_id TEXT REFERENCES contents(id),after_content_id TEXT REFERENCES contents(id),PRIMARY KEY(run_id,relative_path,role));
CREATE TABLE run_summaries(run_id TEXT PRIMARY KEY REFERENCES runs(id),summary_content_id TEXT REFERENCES contents(id),handoff_content_id TEXT REFERENCES contents(id),source_revision INTEGER NOT NULL);
CREATE TABLE ui_state(device_id TEXT NOT NULL REFERENCES devices(id),view TEXT NOT NULL,scope_key TEXT NOT NULL,key TEXT NOT NULL,value_json TEXT NOT NULL,revision INTEGER NOT NULL,PRIMARY KEY(device_id,view,scope_key,key));
CREATE TABLE leases(resource_id TEXT NOT NULL REFERENCES objects(id),purpose TEXT NOT NULL,owner_runtime_id TEXT NOT NULL REFERENCES runtime_instances(id),generation INTEGER NOT NULL,expires_at INTEGER NOT NULL,PRIMARY KEY(resource_id,purpose));
CREATE TABLE schedule_firings(schedule_id TEXT NOT NULL REFERENCES schedules(id),occurrence_key TEXT NOT NULL,task_id TEXT NOT NULL REFERENCES tasks(id),status TEXT NOT NULL,PRIMARY KEY(schedule_id,occurrence_key));
CREATE TABLE events(id TEXT PRIMARY KEY,sequence INTEGER NOT NULL UNIQUE,subject_id TEXT REFERENCES objects(id),actor_id TEXT NOT NULL REFERENCES actors(id),kind TEXT NOT NULL,content_id TEXT NOT NULL REFERENCES contents(id),created_at INTEGER NOT NULL,request_id TEXT NOT NULL REFERENCES requests(id));
CREATE TABLE requests(actor_id TEXT NOT NULL REFERENCES actors(id),idempotency_key TEXT NOT NULL,id TEXT NOT NULL UNIQUE,input_hash TEXT NOT NULL,result_content_id TEXT REFERENCES contents(id),status TEXT NOT NULL,committed_sequence INTEGER,PRIMARY KEY(actor_id,idempotency_key));
CREATE TABLE outbox(id TEXT PRIMARY KEY,event_id TEXT NOT NULL REFERENCES events(id),channel TEXT NOT NULL,destination_ref TEXT NOT NULL,content_id TEXT NOT NULL REFERENCES contents(id),generation INTEGER NOT NULL,state TEXT NOT NULL,attempt INTEGER NOT NULL DEFAULT 0,next_attempt_at INTEGER,UNIQUE(event_id,channel,destination_ref,generation));
CREATE TABLE inbox(channel TEXT NOT NULL,source_id TEXT NOT NULL,content_id TEXT NOT NULL REFERENCES contents(id),state TEXT NOT NULL,acknowledged_at INTEGER,PRIMARY KEY(channel,source_id));
CREATE TABLE projections(namespace TEXT NOT NULL,scope_key TEXT NOT NULL,projection_key TEXT NOT NULL,source_sequence INTEGER NOT NULL,expires_at INTEGER,content_id TEXT NOT NULL REFERENCES contents(id),last_error TEXT,PRIMARY KEY(namespace,scope_key,projection_key));
CREATE TABLE growth_items(snapshot_id TEXT NOT NULL REFERENCES growth_snapshots(id),item_id TEXT NOT NULL,parent_id TEXT,kind TEXT NOT NULL,relative_path TEXT,label TEXT NOT NULL,metrics_json TEXT,production_files INTEGER,test_files INTEGER,test_cases INTEGER,bytes INTEGER,PRIMARY KEY(snapshot_id,item_id),FOREIGN KEY(snapshot_id,parent_id) REFERENCES growth_items(snapshot_id,item_id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE growth_edges(snapshot_id TEXT NOT NULL,source_item_id TEXT NOT NULL,target_item_id TEXT NOT NULL,kind TEXT NOT NULL,weight REAL,evidence_id TEXT REFERENCES evidence(id),PRIMARY KEY(snapshot_id,source_item_id,target_item_id,kind),FOREIGN KEY(snapshot_id,source_item_id) REFERENCES growth_items(snapshot_id,item_id),FOREIGN KEY(snapshot_id,target_item_id) REFERENCES growth_items(snapshot_id,item_id));
CREATE TABLE growth_signals(snapshot_id TEXT NOT NULL,signal_key TEXT NOT NULL,item_id TEXT NOT NULL,type TEXT NOT NULL,level TEXT NOT NULL,value TEXT,evidence_id TEXT REFERENCES evidence(id),PRIMARY KEY(snapshot_id,signal_key),FOREIGN KEY(snapshot_id,item_id) REFERENCES growth_items(snapshot_id,item_id));
CREATE INDEX objects_scope_kind ON objects(project_id,kind,archived_at,updated_at,id);
CREATE VIRTUAL TABLE object_search USING fts5(terms,content='',contentless_delete=1,detail=none);
CREATE INDEX events_subject_sequence ON events(subject_id,sequence);
CREATE INDEX log_chunks_order ON log_chunks(run_id,stream,byte_offset);
CREATE INDEX outbox_delivery ON outbox(state,next_attempt_at);
`;
  const entities = Object.entries(entityDefinitions).map(([kind, definition]) => {
    const scope = definition.project ? ' NOT NULL' : '';
    const projectTargets = new Set([...Object.values(entityDefinitions).filter(item => item.project).map(item => item.table), 'project_locations']);
    const references = [...definition.columns.matchAll(/([a-z_]+) TEXT(?: NOT NULL)? REFERENCES ([a-z_]+)\(id\)/g)]
      .filter(match => projectTargets.has(match[2]))
      .map(match => `FOREIGN KEY(${match[1]},project_id) REFERENCES ${match[2]}(id,project_id)`);
    return `CREATE TABLE ${definition.table}(id TEXT PRIMARY KEY,object_kind TEXT NOT NULL DEFAULT '${kind}' CHECK(object_kind='${kind}'),project_id TEXT${scope},${definition.columns},UNIQUE(id,project_id),FOREIGN KEY(id,object_kind) REFERENCES objects(id,kind),FOREIGN KEY(id,project_id) REFERENCES objects(id,project_id)${references.length ? ',' + references.join(',') : ''}${definition.constraints ? ',' + definition.constraints : ''});
CREATE TRIGGER ${definition.table}_scope_insert BEFORE INSERT ON ${definition.table} WHEN NOT EXISTS(SELECT 1 FROM objects WHERE id=NEW.id AND project_id IS NEW.project_id) BEGIN SELECT RAISE(ABORT,'scope_mismatch'); END;
CREATE TRIGGER ${definition.table}_scope_update BEFORE UPDATE OF project_id ON ${definition.table} WHEN NEW.project_id IS NOT OLD.project_id BEGIN SELECT RAISE(ABORT,'immutable_scope'); END;
CREATE INDEX ${definition.table}_scope ON ${definition.table}(project_id);`;
  }).join('\n');
  return base + entities + `
CREATE TRIGGER roadmap_dependency_scope BEFORE INSERT ON roadmap_dependencies WHEN (SELECT project_id FROM roadmap_nodes WHERE id=NEW.node_id) IS NOT (SELECT project_id FROM roadmap_nodes WHERE id=NEW.dependency_id) BEGIN SELECT RAISE(ABORT,'scope_mismatch'); END;
CREATE TRIGGER object_scope_immutable BEFORE UPDATE OF project_id,kind ON objects WHEN NEW.project_id IS NOT OLD.project_id OR NEW.kind<>OLD.kind BEGIN SELECT RAISE(ABORT,'immutable_identity'); END;`;
}
